---
Name: partialformroutes
After:
  - '#rootroutes'
---
SilverStripe\Control\Director:
  rules:
    'partialfiledownload/$Key/$Token/$FieldName': Firesphere\PartialUserForms\Controllers\PartialFileDownloadController
    'partialuserform//$Action/$ID/$OtherID': Firesphere\PartialUserForms\Controllers\PartialSubmissionController
    'partial/$Key/$Token': Firesphere\PartialUserForms\Controllers\PartialUserFormController
